### ISSUE TITLE
【bug】流程图详情数据显示不全

### ISSUE THREAD

**Issue by AaronWang3369** [anyilanxin/anyi-cloud#2]
1. 审批信息没有正确显示 
![image](https://user-images.githubusercontent.com/16057795/210527190-29f4117c-97d2-4fbd-b33c-8db26fe3c61a.png)

2. 操作类型也没有正确显示。并且没有看出来哪个字段对应操作类型 
3. 审批状态有字典说明吗？

**Comment by zxuanhong** [comment]
@AaronWang3369 请使用最新流程框架
[anyi-process-ee-demo-antvue](https://github.com/anyilanxin/anyi-process-ee-demo-antvue)
